Corrected round-robin config for component renames made by 1774288
mozilla/relman-auto-nag pull request #1521
Opened 2022-07-06 15:18 UTC by b0bh00d

## Checklist

- [ ] Type annotations added to new functions
- [ ] Docs added to functions touched in main classes
- [ ] Dry-run produced the expected results
- [ ] The [`to-be-announced`](https://github.com/mozilla/relman-auto-nag/labels/to-be-announced) tag added if this is worth announcing

2022-07-06 15:59 UTC, calixteman approved these changes

2022-07-06 16:06 UTC, calixteman requested changes
Sorry, I reviewed a bit too fastly this patch.
As @suhaibmujahid noticed, the names here should be `product`::`component`.
For example for the first one we should have `Core::Graphics: Canvas2D` (it was likely wrong before the change on bugzilla).

2022-07-06 16:39 UTC, suhaibmujahid commented
Based on the names on Bugzilla, the names in the round-robin config should look as follows:
```
{
    "Core::Graphics": "default",
    "Core::Graphics: Canvas2D": "default",
    "Core::Graphics: CanvasWebGL": "default",
    "Core::Graphics: Color Management": "default",
    "Core::Graphics: Image Blocking": "default",
    "Core::Graphics: ImageLib": "default"
    "Core::Graphics: Layers": "default",
    "Core::Graphics: Text": "default",
    "Core::Graphics: WebRender": "default",
}
```

I noticed that `Core::Graphics: WebGPU` is not in the list. On the other side, `Core::Graphics: Layers` is in the list even though it is marked as inactive on Bugzilla.

2022-07-07 15:24 UTC, b0bh00d commented
> (it was likely wrong before the change on bugzilla)

Looks likely that it was.  I have to wonder if it was even working.

> On the other side, `Core::Graphics: Layers` is in the list even though it is marked as inactive on Bugzilla.

Yes, `Core::Graphics: Layers` was disabled by 1774288.  I'll remove it from the list.

2022-07-07 15:34 UTC, suhaibmujahid approved these changes
Thank you @b0bh00d! LGTM.

2022-07-07 16:01 UTC, calixteman approved these changes

2022-07-07 16:02 UTC, merged